config/routes.rb
SwipeBook::Application.routes.draw do
  resources :passages

  root :to => 'passages#index'

end

app/models/passage.rb
class Passage < ActiveRecord::Base
  attr_accessible :author, :page, :quote, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/passages_controller.rb
class PassagesController < ApplicationController
  # GET /passages
  # GET /passages.json
  def index
    @passages = Passage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @passages }
    end
  end

  # GET /passages/1
  # GET /passages/1.json
  def show
    @passage = Passage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @passage }
    end
  end

  # GET /passages/new
  # GET /passages/new.json
  def new
    @passage = Passage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @passage }
    end
  end

  # GET /passages/1/edit
  def edit
    @passage = Passage.find(params[:id])
  end

  # POST /passages
  # POST /passages.json
  def create
    @passage = Passage.new(params[:passage])

    respond_to do |format|
      if @passage.save
        format.html { redirect_to @passage, notice: 'Passage was successfully created.' }
        format.json { render json: @passage, status: :created, location: @passage }
      else
        format.html { render action: "new" }
        format.json { render json: @passage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /passages/1
  # PUT /passages/1.json
  def update
    @passage = Passage.find(params[:id])

    respond_to do |format|
      if @passage.update_attributes(params[:passage])
        format.html { redirect_to @passage, notice: 'Passage was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @passage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passages/1
  # DELETE /passages/1.json
  def destroy
    @passage = Passage.find(params[:id])
    @passage.destroy

    respond_to do |format|
      format.html { redirect_to passages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/passages_helper.rb
module PassagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SwipeBook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<meta http-equiv="X-UA-Compatible" content="IE=8">
	<meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0'/> 
	<link href='/style.css' rel='stylesheet'/>
	<script type="text/javascript" src="swipe.js"></script>
	<style>

	/* Swipe 2 required styles */

	.swipe {
		overflow: hidden;
		visibility: hidden;
		position: relative;
	}
	.swipe-wrap {
		overflow: hidden;
		position: relative;
	}
	.swipe-wrap > div {
		float:left;
		width:100%;
		position: relative;
	}

	/* END required styles */

	</style>
</head>





<body>

<%= yield %>


<script src='/swipe.js'></script>
<script>

// pure JS
var elem = document.getElementById('mySwipe');
window.mySwipe = Swipe(elem, {
  // startSlide: 4,
  // auto: 3000,
  // continuous: true,
  // disableScroll: true,
  // stopPropagation: true,
  // callback: function(index, element) {},
  // transitionEnd: function(index, element) {}
});

// with jQuery
// window.mySwipe = $('#mySwipe').Swipe().data('Swipe');

</script>

</body>
</html>

app/views/passages/_form.html.erb
<%= form_for(@passage) do |f| %>
  <% if @passage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@passage.errors.count, "error") %> prohibited this passage from being saved:</h2>

      <ul>
      <% @passage.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quote %><br />
    <%= f.text_area :quote %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :page %><br />
    <%= f.number_field :page %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/passages/edit.html.erb
<h1>Editing passage</h1>

<%= render 'form' %>

<%= link_to 'Show', @passage %> |
<%= link_to 'Back', passages_path %>

app/views/passages/index.html.erb
<h1>Notes</h1>

<div id='mySwipe' style='max-width:500px;margin:0 auto' class='swipe'>
  <div class='swipe-wrap'>

    <!-- This is a thing -->
    


    <% @passages.each do |passage| %>
    <div>

      <h3><%= passage.title %> </h3>
      <i>
        "<%= passage.quote %>"  
        
         
      </i>
      <center>
      <b><%= passage.author %></b> <span> Page: <%= passage.page %> </span>
      </center>

      <center>
     <%= link_to 'Show', passage %> 
     <%= link_to 'Edit', edit_passage_path(passage) %> 
     <%= link_to 'Destroy', passage, method: :delete, data: { confirm: 'Are you sure?' } %> 
     </center>
    </div>
     
     <% end %>
    <!-- k -->
  </div>
</div>



<div style='text-align:center;padding-top:20px;'>
  
  <button onclick='mySwipe.prev()'>prev</button> 
  <button onclick='mySwipe.next()'>next</button>

</div>


<%= link_to 'New Passage', new_passage_path %>

app/views/passages/new.html.erb
<h1>New passage</h1>

<%= render 'form' %>

<%= link_to 'Back', passages_path %>

app/views/passages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Quote:</b>
  <%= @passage.quote %>
</p>

<p>
  <b>Title:</b>
  <%= @passage.title %>
</p>

<p>
  <b>Page:</b>
  <%= @passage.page %>
</p>

<p>
  <b>Author:</b>
  <%= @passage.author %>
</p>


<%= link_to 'Edit', edit_passage_path(@passage) %> |
<%= link_to 'Back', passages_path %>